### ISSUE TITLE
Convert cn to ct when only cn exists

### ISSUE THREAD

**Issue by nelliemckesson** [macmillanpublishers/WordXML-to-HTML#12]
In documents where only a chapter number is used to start chapters, and the chapter number is styled as ChapNumbercn, restyle all ChapNumbercn paragraphs as ChapTitlect.

**Comment by nelliemckesson** [comment]
@ericawarren I'd like to see if we can do this via the powershell script. Do some investigating, and if it's not possible, you can assign back to me and I'll do it via XSL.

**Comment by ericawarren** [comment]
We could also build it into either the cleanup Word macro or the bookmaker requirements Word macro if it doesn't work with Powershell.

**Comment by nelliemckesson** [comment]
Oh yeah, if it's possible to build it into a macro, we should do that!
